[build]
   before_build = "curl -O https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.10.0-stable.tar.xz && tar xf flutter_linux_2.10.0-stable.tar.xz && export PATH=\"$PATH:`pwd`/flutter/bin\""
