name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x' # or the version you're using

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
