on:
  push:
    branches:
      - master

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get

      - name: Get version from pubspec.yaml
        id: get_version
        run: echo ::set-output name=VERSION::$(grep -o 'version: .*' pubspec.yaml | awk '{print $2}')

      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v${{ steps.get_version.outputs.VERSION }}
          token: ${{ secrets.TOKEN }}
